django_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_shop_app.urls')),
]

django_shop_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "django_shop_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.custom_logout, name='logout'),
    path('c/<int:category_id>/', views.category_products, name='category_products'),
    path('p/<int:product_id>/', views.product_detail, name='product_detail'),
    path('cart/', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('order_confirmation/', views.order_confirmation, name='order_confirmation'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    path('admin_panel/add_category/', views.add_category, name='add_category'),
    path('admin_panel/add_product/', views.add_product, name='add_product'),
    path('admin_panel/category_list/', views.category_list, name='category_list'),
    path('admin_panel/delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('admin_panel/product_list/', views.product_list, name='product_list'),
    path('admin_panel/edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('admin_panel/delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('admin_panel/order_list/', views.order_list, name='order_list'),
    path('admin_panel/order_details/<int:order_id>/', views.order_details, name='order_details'),
    path('user_panel/', views.user_panel, name='user_panel'),
    path('user_panel/user_orders/', views.user_orders, name='user_orders'),
    path('change_password/', views.change_password, name='change_password'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to=settings.PRODUCT_IMAGES_DIR, default='product_images/default.jpg')

    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField('Product', through='CartItem')

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address = models.TextField()
    phone_number = models.CharField(max_length=20)
    created_at = models.DateTimeField(default=timezone.now)
    products = models.ManyToManyField('Product', through='OrderItem')

    def __str__(self):
        return f'Order #{self.pk} - {self.first_name} {self.last_name}'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.product.name} x {self.quantity}'

django_shop_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .models import Category, Product

class CustomUserCreationForm(UserCreationForm):   
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = None 
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

        self.fields['username'].label = 'Nazwa użytkownika'
        self.fields['password1'].label = 'Hasło'
        self.fields['password2'].label = 'Potwierdź hasło'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
            'name': 'Nazwa kategorii',
        }

class ProductForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label='Kategoria')
    
    class Meta:
        model = Product
        fields = ['category', 'name', 'description', 'price', 'image']
        labels = {
            'name': 'Nazwa produktu',
            'description': 'Opis produktu',
            'price': 'Cena',
            'image': 'Obraz produktu',
        }

class CheckoutForm(forms.Form):
    first_name = forms.CharField(label='Imię')
    last_name = forms.CharField(label='Nazwisko')
    address = forms.CharField(label='Adres', widget=forms.Textarea)
    phone_number = forms.CharField(label='Numer telefonu')

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].label = 'Stare hasło'
        self.fields['new_password1'].label = 'Nowe hasło'
        self.fields['new_password2'].label = 'Potwierdź nowe hasło'

        self.fields['new_password1'].help_text = None

django_shop_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .forms import CustomUserCreationForm, CategoryForm, ProductForm, CheckoutForm, CustomPasswordChangeForm
from .models import Product, Category, Cart, CartItem, Order, OrderItem

def index(request):
    categories = Category.objects.all()
    latest_products = Product.objects.order_by('-id')[:3]
    
    context = {
        'categories': categories,
        'products': latest_products,
        'on_home_page': True,
    }

    return render(request, 'django_shop_app/index.html', context)

def login_view(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('django_shop_app:index')
    return render(request, 'django_shop_app/login.html', {'categories': categories})

def register_view(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('django_shop_app:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'django_shop_app/register.html', {'form': form, 'categories': categories})

def custom_logout(request):
    logout(request)
    return redirect('django_shop_app:index')

def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('django_shop_app:admin_panel')
    else:
        form = CategoryForm()
    return render(request, 'django_shop_app/add_category.html', {'form': form})

def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('django_shop_app:admin_panel')
    else:
        form = ProductForm()
    return render(request, 'django_shop_app/add_product.html', {'form': form})

def category_products(request, category_id):
    categories = Category.objects.all()
    category_products = Product.objects.filter(category_id=category_id)
    
    context = {
        'categories': categories,
        'products': category_products,
        'on_home_page': False,
    }

    return render(request, 'django_shop_app/index.html', context)

def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    categories = Category.objects.all()
    return render(request, 'django_shop_app/product.html', {'product': product, 'categories': categories})

def admin_panel(request):
    categories = Category.objects.all()

    context = {
        'categories': categories,
    }

    return render(request, 'django_shop_app/admin_panel.html', context)

def category_list(request):
    categories = Category.objects.all()
    return render(request, 'django_shop_app/category_list.html', {'categories': categories})

def delete_category(request, category_id):
    if request.method == 'POST':
        category = Category.objects.get(pk=category_id)
        category.delete()
    return redirect('django_shop_app:admin_panel')

def product_list(request):
    products = Product.objects.all()

    context = {
        'products': products,
    }

    return render(request, 'django_shop_app/product_list.html', context)

def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('django_shop_app:admin_panel')
    else:
        form = ProductForm(instance=product)
    return render(request, 'django_shop_app/edit_product.html', {'form': form, 'product': product})

def delete_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    return redirect('django_shop_app:admin_panel')

@login_required(login_url='/login/')
def add_to_cart(request, product_id):
    user = request.user
    product = get_object_or_404(Product, pk=product_id)
    quantity = int(request.POST.get('quantity', 1))

    cart, created = Cart.objects.get_or_create(user=user)
    cart_item, item_created = CartItem.objects.get_or_create(cart=cart, product=product)

    if not item_created:
        cart_item.quantity += quantity
        cart_item.save()
    else:
        cart_item.quantity = quantity
        cart_item.save()

    return redirect('django_shop_app:cart')

@login_required(login_url='/login/')
def cart(request):
    categories = Category.objects.all()

    try:
        cart = request.user.cart
        cart_items = CartItem.objects.filter(cart=cart)
    except Cart.DoesNotExist:
        cart = Cart.objects.create(user=request.user)
        cart_items = []

    total_price = 0
    for item in cart_items:
        item.total_price = item.quantity * item.product.price
        total_price += item.total_price
    
    context = {
        'cart_items': cart_items,
        'total_price': total_price,
        'categories': categories
    }
    return render(request, 'django_shop_app/cart.html', context)


def remove_from_cart(request, product_id):
    cart_item = CartItem.objects.get(cart=request.user.cart, product_id=product_id)
    cart_item.delete()
    return redirect('django_shop_app:cart')

@login_required(login_url='/login/')
def checkout(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            cart_items = CartItem.objects.filter(cart=request.user.cart)
            if cart_items:
                order = Order(
                    user=request.user,
                    first_name=form.cleaned_data['first_name'],
                    last_name=form.cleaned_data['last_name'],
                    address=form.cleaned_data['address'],
                    phone_number=form.cleaned_data['phone_number']
                )
                order.save()

                for cart_item in cart_items:
                    OrderItem.objects.create(order=order, product=cart_item.product, quantity=cart_item.quantity)

                cart_items.delete()

                return redirect('django_shop_app:order_confirmation')
            else:
                return redirect('django_shop_app:cart')
    else:
        form = CheckoutForm()
    return render(request, 'django_shop_app/checkout.html', {'form': form, 'categories': categories})

def order_confirmation(request):
    categories = Category.objects.all()

    context = {
        'categories': categories
    }
    return render(request, 'django_shop_app/order_confirmation.html', context)

def order_list(request):
    orders = Order.objects.all()

    for order in orders:
        total_price = 0
        for order_item in order.orderitem_set.all():
            total_price += order_item.product.price * order_item.quantity
        order.total_price = total_price

    context = {'orders': orders}
    return render(request, 'django_shop_app/order_list.html', context)

def order_details(request, order_id):
    order = Order.objects.get(pk=order_id)
    order_items = order.orderitem_set.all()

    total_price = sum(item.product.price * item.quantity for item in order_items)

    context = {'order': order, 'order_items': order_items, 'total_price': total_price}
    return render(request, 'django_shop_app/order_details.html', context)

def user_panel(request):
    categories = Category.objects.all()

    context = {
        'categories': categories,
    }

    return render(request, 'django_shop_app/user_panel.html', context)

@login_required(login_url='/login/')
def user_orders(request):
    orders = Order.objects.filter(user=request.user)

    for order in orders:
        total_price = 0
        order_items = order.orderitem_set.all()  # Zwraca wszystkie elementy zamówienia dla danego zamówienia
        for order_item in order_items:
            total_price += order_item.quantity * order_item.product.price

        order.total_price = total_price  # Dodajemy pole total_price do każdego zamówienia

    return render(request, 'django_shop_app/user_orders.html', {'orders': orders})


def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)  # Użyj niestandardowej klasy formularza
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('django_shop_app:index')
    else:
        form = CustomPasswordChangeForm(request.user)
    return render(request, 'django_shop_app/change_password.html', {'form': form})

django_shop_app/templates/django_shop_app/admin_panel.html
{% extends 'django_shop_app/base.html' %}

{% block title %}
Panel administratora
{% endblock %}

{% block content %}
<div class="admin-panel">
    <div class="admin-options">
        <ul>
            <button id="add-category-btn">Dodaj kategorię</button>
            <button id="add-product-btn">Dodaj produkt</button>
            <button id="category-list-btn">Lista kategorii</button>
            <button id="add-product-list-btn">Lista produktów</button>
            <button id="order-list-btn">Lista zamówień</button>
            <button id="change-password-btn">Zmiana hasła</button>
        </ul>
    </div>
    <div class="admin-content"></div>
</div>
<script>
$(document).ready(function() {
    $('#add-category-btn').click(function() {
        $('.admin-content').load('/admin_panel/add_category/');
    });
    $('#add-product-btn').click(function() {
        $('.admin-content').load('/admin_panel/add_product/');
    });
    $('#category-list-btn').click(function() {
        $('.admin-content').load('/admin_panel/category_list/');
    });
    $('#add-product-list-btn').click(function() {
        $('.admin-content').load('/admin_panel/product_list/');
    });
    $('#order-list-btn').click(function() {
        $('.admin-content').load('/admin_panel/order_list/');
    });
    $('#change-password-btn').click(function() {
        $('.admin-content').load('/change_password/');
    });
});
</script>
{% endblock %}

django_shop_app/templates/django_shop_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Strona Główna{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static '/django_shop_app/index.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
    <header>
        <div class="main-header">
            <div class="header-logo">
                <a href="/">
                    <img src="{% static '/django_shop_app/logo.png' %}" alt="">
                </a>
            </div>
            <nav class="main-nav">
                <ul class="category-list">
                    {% for category in categories %}
                        <li><a href="/c/{{ category.id }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
            <div class="header-content">
                <div class="header-icons">
                    <a href="#" class="search-icon"><img src="{% static '/django_shop_app/search.png' %}" alt="Wyszukiwarka"></a>
                    <a href="/cart" class="cart-icon"><img src="{% static '/django_shop_app/shopping-cart.png' %}" alt="Koszyk"></a>
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <a href="/admin_panel" class="admin-icon"><img src="{% static '/django_shop_app/admin.png' %}" alt="Admin"></a>
                        {% else %}
                            <a href="/user_panel" class="admin-icon"><img src="{% static '/django_shop_app/user.png' %}" alt="User"></a>
                        {% endif %}
                        <a href="/logout" class="user-icon"><img src="{% static '/django_shop_app/logout.png' %}" alt="Wyloguj"></a>
                    {% else %}
                        <a href="/login" class="user-icon"><img src="{% static '/django_shop_app/login.png' %}" alt="Zaloguj"></a>
                    {% endif %}
                </div>
                {% if user.is_authenticated %}
                    <div class="user-info">
                        <span>Zalogowany jako:</span>
                        <span>{{ user.username }}</span>
                    </div>
                {% endif %}
            </div>            
        </div>
    </header>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

django_shop_app/templates/django_shop_app/cart.html
{% extends 'django_shop_app/base.html' %}
{% load static %}

{% block title %}
Twój koszyk
{% endblock %}

{% block content %}
<div class="cart-page">
    {% if cart_items %}
    <table>
        <tbody>
            {% for item in cart_items %}
            <tr>
                <td>
                    <img src="{{ item.product.image.url }}" alt="{{ item.product.name }} image">
                </td>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.product.price }} PLN</td>
                <td>{{ item.total_price }} PLN</td>
                <td>
                    <form method="post" action="{% url 'django_shop_app:remove_from_cart' item.product.id %}">
                        {% csrf_token %}
                        <button type="submit" class="remove-button"><img src="{% static '/django_shop_app/x.png' %}" alt="Usuń"></button>
                    </form>
                </td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="4">Łącznie:</td>
                <td>{{ total_price }} PLN</td>
            </tr>
        </tbody>
    </table>
    <a href="{% url 'django_shop_app:checkout' %}" class="checkout-button">Przejdź do finalizacji zamówienia</a>
    {% else %}
    <p>Koszyk jest pusty.</p>
    {% endif %}
</div>
{% endblock %}

django_shop_app/templates/django_shop_app/category_list.html
{% block content %}
<div class="product-list">
    <table>
        <thead>
            <tr>
                <th>Nazwa kategorii</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <td>{{ category.name }}</td>
                <td>
                    <form method="post" action="{% url 'django_shop_app:delete_category' category.id %}">
                        {% csrf_token %}
                        <button type="submit">Usuń</button>
                    </form>
                </td>                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% endblock %}

django_shop_app/templates/django_shop_app/checkout.html
{% extends 'django_shop_app/base.html' %}

{% block title %}
Finalizacja Zamówienia
{% endblock %}

{% block content %}
<div class="checkout-page">
    <h2>Finalizacja Zamówienia</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Złóż Zamówienie</button>
    </form>
</div>
{% endblock %}

django_shop_app/templates/django_shop_app/edit_product.html
{% block content %}
<div class="edit-product">
    <form method="post" action="/admin_panel/edit_product/{{ product.id }}/" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zapisz zmiany</button>
    </form>
</div>
{% endblock %}

django_shop_app/templates/django_shop_app/login.html
{% extends 'django_shop_app/base.html' %}

{% block title %}
Logowanie
{% endblock %}

{% block content %}
<div class="auth-page">
    <h2>Logowanie</h2>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="username">Nazwa użytkownika:</label>
            <input type="text" id="username" name="username" required>
        </div>
        <div>
            <label for="password">Hasło:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <button type="submit">Zaloguj</button>
    </form>
    <form method="get" action="/register">
        <button type="submit">Zarejestruj się</button>
    </form>
</div>
{% endblock %}

django_shop_app/templates/django_shop_app/order_confirmation.html
{% extends 'django_shop_app/base.html' %}

{% block title %}
Potwierdzenie zamówienia
{% endblock %}

{% block content %}
<div class="order-confirmation">
    <h2>Potwierdzenie zamówienia</h2>
    <p>Dziękujemy za złożenie zamówienia.</p>
</div>
{% endblock %}

django_shop_app/templates/django_shop_app/order_list.html
{% block content %}
<div class="product-list">
    <table>
        <thead>
            <tr>
                <th>Numer zamówienia</th>
                <th>Data zamówienia</th>
                <th>Klient</th>
                <th>Suma</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.created_at }}</td>
                <td>{{ order.user }}</td>
                <td>{{ order.total_price }} PLN</td>
                <td>
                    <button type="submit" class="order-details-btn" data-order-id="{{ order.id }}">Szczegóły</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function() {
    $('.order-details-btn').click(function() {
        var orderId = $(this).data('order-id');
        $.get('/admin_panel/order_details/' + orderId + '/', function(data) {
            $('.admin-content').html(data);
        });
    });
});
</script>
{% endblock %}

django_shop_app/templates/django_shop_app/product.html
{% extends 'django_shop_app/base.html' %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-details-page">
        <div class="product-image">
            <img src="{{ product.image.url }}" alt="{{ product.name }} image">
        </div>
        <div class="product-info">
            <h2>{{ product.name }}</h2>
            <p>{{ product.price }} PLN</p>
            <form action="{% url 'django_shop_app:add_to_cart' product.id %}" method="post">
                {% csrf_token %}
                <div class="quantity-container">
                    <label for="quantity">Ilość:</label>
                    <input type="number" id="quantity" name="quantity" value="1" min="1">
                </div>
                <button type="submit">Dodaj do koszyka</button>
            </form>
        </div>        
        <div class="product-description">
            <h3>Opis produktu:</h3>
            <p>{{ product.description }}</p>
        </div>
    </div>
{% endblock %}

django_shop_app/templates/django_shop_app/product_list.html
{% block content %}
<div class="product-list">
    <table>
        <thead>
            <tr>
                <th>Nazwa produktu</th>
                <th>Kategoria</th>
                <th>Cena</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ product.category }}</td>
                <td>{{ product.price }}</td>
                <td>
                    <form method="post" action="{% url 'django_shop_app:delete_product' product.id %}">
                        {% csrf_token %}
                        <button type="submit">Usuń</button>
                    </form>
                    <button type="submit" class="edit-product-btn" data-product-id="{{ product.id }}">Edytuj</button>
                </td>                
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script>
$(document).ready(function() {
    $('.edit-product-btn').click(function() {
        var productId = $(this).data('product-id');
        $.get('/admin_panel/edit_product/' + productId + '/', function(data) {
            $('.admin-content').html(data);
        });
    });
});
</script>
{% endblock %}

django_shop_app/templates/django_shop_app/register.html
{% extends 'django_shop_app/base.html' %}

{% block title %}
Rejestracja
{% endblock %}

{% block content %}
<div class="auth-page">
    <h2>Rejestracja</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zarejestruj</button>
    </form>
</div>
{% endblock %}

django_shop_app/templates/django_shop_app/user_orders.html
{% block content %}
<div class="product-list">
    {% if orders %}
        <table>
            <thead>
                <tr>
                    <th>Numer zamówienia</th>
                    <th>Data zamówienia</th>
                    <th>Suma</th>
                    <th>Szczegóły</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <td>{{ order.pk }}</td>
                        <td>{{ order.created_at }}</td>
                        <td>{{ order.total_price }}</td>
                        <td>
                            <button type="submit" class="order-details-btn" data-order-id="{{ order.id }}">Szczegóły</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Brak zamówień.</p>
    {% endif %}
</div>
<script>
    $(document).ready(function() {
        $('.order-details-btn').click(function() {
            var orderId = $(this).data('order-id');
            $.get('/admin_panel/order_details/' + orderId + '/', function(data) {
                $('.admin-content').html(data);
            });
        });
    });
</script>
{% endblock %}

django_shop_app/templates/django_shop_app/user_panel.html
{% extends 'django_shop_app/base.html' %}

{% block title %}
Panel użytkownika
{% endblock %}

{% block content %}
<div class="admin-panel">
    <div class="admin-options">
        <ul>
            <button id="order-list-btn">Moje zamówienia</button>
            <button id="change-password-btn">Zmiana hasła</button>
        </ul>
    </div>
    <div class="admin-content"></div>
</div>
<script>
$(document).ready(function() {
    $('#order-list-btn').click(function() {
        $('.admin-content').load('/user_panel/user_orders/');
    });
    $('#change-password-btn').click(function() {
        $('.admin-content').load('/change_password/');
    });
});
</script>
{% endblock %}